### ISSUE TITLE
IDEA 15 darkula breaks solarized theme

### ISSUE THREAD

**Issue by steveash** [jkaving/intellij-colors-solarized#112]
They changed something in IDEA 15 that breaks the solarized theme. I have attached a screenshot of the java code appearance using the darkula solarized dark theme.  Note the dark purple for field names is the only thing that seems to get picked up at all.  The rest of the colors just don't get picked up at all.  The dark purple is unreadable too.

http://i.imgur.com/xxYOIoY.png

**Comment by camabeh** [comment]
+1

**Comment by jkaving** [comment]
This is a screenshot of a Java file using Darcula and Solarized Dark (Darcula) on IntelliJ IDEA 15.0.2 on OS X 10.11.2.
![screenshot of intellij idea 2015-12-21 13-14-29](https://cloud.githubusercontent.com/assets/725090/11930584/0bd0af6e-a7e5-11e5-9c27-70a17d1ad8e7.png)

It still matches the official example image for Java code on the Solarized web site:
![Java Solarized Dark](http://ethanschoonover.com/solarized/img/screen-java-dark.png)

I don't know what causes the different behavior for you.
Could it be an issue for only the Linux version?

**Comment by jcohen** [comment]
The main issue for is constants (i.e. static final variables). They're showing up as purple.

![screen shot 2015-12-21 at 8 33 27 am](https://cloud.githubusercontent.com/assets/243198/11932818/acc45380-a7bd-11e5-82b7-550f80630566.png)

This is on Mac OS 10.11.2, IntelliJ 15.0.2.

**Comment by jcohen** [comment]
Btw, if you want, you should be able to replicate this yourself by cloning https://github.com/apache/aurora and running `./gradlew idea` from the project root.

**Comment by jkaving** [comment]
@jcohen Thanks for the comments. Cloning the aurora project and opening the same file worked lika a charm to understand the problem.

It seems as if IntelliJ IDEA 15 has added a color setting for Java constants ( `STATIC_FINAL_FIELD_ATTRIBUTES`):
![screenshot of intellij idea 2015-12-21 16-07-33](https://cloud.githubusercontent.com/assets/725090/11933575/f5348736-a7fc-11e5-94ac-d072f3e0675c.png)

Since this setting is new it will get the default color (a darker purple, bold and italic).
I will add a Solarized color for this, and I will keep them italic (to distinguish them from non-final static fields) but make them regular weight (the rest of the Solarized theme doesn't use bold fonts).

**Comment by jcohen** [comment]
:+1: looks much better now. Thanks @jkaving!

**Comment by camabeh** [comment]
Thanks
