### ISSUE TITLE
Font colour in commit message text box

### ISSUE THREAD

**Issue by dcodrin** [jkaving/intellij-colors-solarized#126]
Please see the below image. Is it possible to change the font colour for the commit messages? 

<img width="636" alt="screen shot 2016-07-01 at 11 37 32 pm" src="https://cloud.githubusercontent.com/assets/12925816/16538072/9684a2a8-3fe5-11e6-89f0-7baccd62c17a.png">

**Comment by aik099** [comment]
Are you using `Solarized Dark (Darcula)` color scheme or just regular `Solarized Dark`?

**Comment by jkaving** [comment]
When i test it there doesn't seem to be any difference between the regular `Solarized Dark` and the `Solarized Dark (Darcula)`.
I think the problem is that the commit dialog is using a different background color than the regular editor, and I have not found a way to change that color using the color scheme file.

**Comment by dcodus** [comment]
> commit dialog is using a different background color

This seems to be the case. The dialog box background has to be changed to account for that, or find a way to load different font colors when in the commit box.
The problem also persists when checking out from version control.
<img width="710" alt="screen shot 2016-07-04 at 4 23 43 pm" src="https://cloud.githubusercontent.com/assets/12925816/16569382/d373145e-4203-11e6-9016-12be3cda07d7.png">

If anyone knows how to change the colors for those specific areas of the IDE or how to change the font colors for those areas please let us know.

**Comment by xxxxxbox** [comment]
I have the same issue in several dialog boxes.
Dark blue font on Dark gray background.
Very hard to read text.
Can't find solution for more than a year.
Tried all phpStorm versions from 9.0 to current 2016.2.1.
I even tried to uninstall phpStorm, delete all setting and make fresh install of phpStorm 2016.2.1. Nothing helps.
Tried preinstalled version of Solarized Light Theme and tried Solarized Light (Darcula) imported through settings.jar file.

I can't find in settings how i can change color or background for this dialogs.
But if a change color theme to preinstalled e.g. "WarmNeon" I can see that font color in these fields changes. Background stay put without changes but white or yellow font color is more readable in these fields. So i understand that color theme can change at least font color to fix the problem.

Please find images bellow
![95c2b9c3f97b4e4d96b034228099bf99](https://cloud.githubusercontent.com/assets/22045985/18302382/44303a14-74e0-11e6-8404-d803f69809fe.png)
![f019e008ef5f4a208b6e60cf6d767a97](https://cloud.githubusercontent.com/assets/22045985/18302381/442ef6ea-74e0-11e6-8dfd-35707aedb0e7.png)
![phpstorm3](https://cloud.githubusercontent.com/assets/22045985/18302961/524dfc78-74e3-11e6-8527-271bd5948c10.png)

**Comment by jkaving** [comment]
I have experimented with this a bit.

It seems as if IntelliJ IDEA will use the default text color (`#586E75` for Solarized Light) in dialogs. When you use the Darcula Look&Feel the dialog background will be dark and the text will be hard to read.
The same problem exists for Solarized Dark (since the Darcula background is lighter than the Solarized Dark background) but it is not as severe as for Solarized Light.

Unfortunately this problem seems hard to fix in the Solarized color scheme, and the solution might be to only use Solarized Dark with the Darcula Look&Feel and Solarized Light with the default Look&Feel.

I think this is a problem in IntelliJ IDEA.
Because color schemes cannot alter the background color of dialogs I don't think that the color scheme should alter the text color in them either.

**Comment by jkaving** [comment]
I found an issue at Jetbrains here:
https://youtrack.jetbrains.com/issue/IDEA-131325

An another one here with more discussion:
https://youtrack.jetbrains.com/issue/IDEA-131109
This one is unfortunately closed.

**Comment by xxxxxbox** [comment]
Thank you for support.
Let's hope Jetbrains will somewhen fix this issue.

**Comment by digitalle** [comment]
This is still an open issue - considering it's probably one of the most used features, i.e. entering commit messages it seems odd that this has fallen off the radar

**Comment by rcavalcanti** [comment]
You can tweak it in:
Settings > Editor > Color & Fonts > General

On the right pane open "Text" and select "Default text".
Change the foreground to something with better contrast.

The downside of it is that it also change the color of some texts in the editor. If you have a light theme for your editor, this can be tricky. You will need to find a dark tone offering enough contrast with the background of the IDE.

**Comment by rcavalcanti** [comment]
![screen shot 2017-07-21 at 23 26 17](https://user-images.githubusercontent.com/502982/28483316-ea877900-6e6c-11e7-8d63-caa916d9baec.png)
