### ISSUE TITLE
Add support to Groovy

### ISSUE THREAD

**Issue by neoecos** [jkaving/intellij-colors-solarized#130]
There is not support for Groovy, used in Gradle files.

**Comment by jkaving** [comment]
Groovy is supported.
The problem is most likely that you need to associate `*.gradle` files with Groovy.

I solved this by right-clicking on a `build.gradle` file and selecting `Associate with File Type`, and then selecting Groovy in the dialog that appeared:
<img width="581" alt="screenshot of intellij idea 2016-08-13 13-57-00" src="https://cloud.githubusercontent.com/assets/725090/17643055/1f97d8d2-615e-11e6-845e-6783299888dd.png">

Please try this and see if it works.
