### ISSUE TITLE
Support for new file status colors

### ISSUE THREAD

**Issue by koraktor** [jkaving/intellij-colors-solarized#143]
It looks like the 2017.1 series of JetBrains IDEs comes with new options for file status colors.

![File Status](https://cloud.githubusercontent.com/assets/66112/24273729/40e9dd6c-1024-11e7-9e1e-20d4d7ba5a9e.png)

**Comment by jkaving** [comment]
This seems to be an intentional change in IntelliJ IDEA.
See [this comment](https://youtrack.jetbrains.com/issue/IDEA-166300#comment=27-1836144) in Youtrack issue IDEA-166300:

> File status colors are not available for custom color schemes. If you need to modify them, you need to select either Default or Darcula (depending on UI theme which you are currently using) and then go back to your own editor scheme. In the future this section will be taken out from Editor|Colors and Fonts since it defines colors for the rest of UI which may not be consistent with the selected editor scheme.

But this shouldn't be a problem - since commit dc6aeea86aff2ef147bab0f6e41bde292c5fd738 the `intellij-colors-solarized` scheme no longer sets any file status colors, they will be inherited from the Default or Darcula color schemes
