### ISSUE TITLE
Colors do not match spec

### ISSUE THREAD

**Issue by kikin81** [jkaving/intellij-colors-solarized#152]
I am writing to note that the colors in this project do not match the (Solarized Project)[http://ethanschoonover.com/solarized]. I am wondering if this is as design or if I am doing something wrong.
![screen shot 2017-07-17 at 2 18 13 pm 1](https://user-images.githubusercontent.com/834204/28290321-dcd47152-6afa-11e7-8d94-4a490380fcac.png)
This repo

![screen-java-dark](https://user-images.githubusercontent.com/834204/28290324-df114aa8-6afa-11e7-9da2-e2a5d28cb07c.png)
Spec

**Comment by jkaving** [comment]
Hi.
Some of it is intentional (for comments e.g. you can read the long discussion in #67 and #127) and some of it is because the syntax highlighting works differently in Vim and IntelliJ IDEA.

The intention is to follow the Solarized examples, but it will probably never be perfect and instead we try to at least limit to using only the 16 Solarized colors (as far as possible).
