### ISSUE TITLE
.cshtml file in Rider has wrong color for html tags

### ISSUE THREAD

**Issue by bradleylandis** [jkaving/intellij-colors-solarized#154]
html files have the tag names in blue and bold, but in the .cshtml file it comes out dark red on the dark blue background and is difficult to read.

![image](https://user-images.githubusercontent.com/325334/28540842-bc8dccba-7084-11e7-98a0-76e2e6d165db.png)

**Comment by jkaving** [comment]
As noted in #150 there is very little support for Rider/C#/.NET

Pull requests for this would be welcome.

**Comment by bradleylandis** [comment]
@jkaving If you can point me in the right direction, I'd love to help out.

**Comment by jkaving** [comment]
I usually use the Preferences dialog in IntelliJ IDEA (under `Editor`->`Color Scheme`) to tweak the colors, trying to limit myself to [the official Solarized colors](http://ethanschoonover.com/solarized#the-values).

In the top of the dialog it is possible to select which scheme to modify (Solarized Light or Dark - the Darcula versions can be skipped since they are automatically generated by the build script in this repo).

After saving the changes I usually copy the color scheme files from the IntelliJ IDEA preferences directory to my working copy of this repo (see [the manual installation section](https://github.com/jkaving/intellij-colors-solarized#option-2-manual-installation) in the README for the location for different OSes).
The diff might need to be inspected a bit since there might be unnecessary changes that IDEA has done when saving the color scheme file, but it is usually relatively easy to figure out which changes correspond to the changes made in the Preferences dialog.

Before committing the changes I try to make sure to run the `buildjar.sh` script to generate an updated version of the `settings.jar` file and include that in the commit.

**Comment by bradleylandis** [comment]
Thanks.  I gave it a shot, but it's not working.  I filed a bug with Rider team https://youtrack.jetbrains.com/issue/RIDER-8913?query=colors%20asp.net

**Comment by bradleylandis** [comment]
The rider team says this bug was fixed in 2017.2 which is out now.  I haven't verified it yet.

**Comment by bradleylandis** [comment]
okay, I may have misunderstood... it looks like they marked it "To be fixed in 2017.2" but it doesn't appear to be fixed in the current EAP of 2017.2

**Comment by bradleylandis** [comment]
I can confirm this is fixed in 2017.2 EAP 2.  You can close this issue

**Comment by jkaving** [comment]
Perfect - thanks for letting us know!
