### ISSUE TITLE
Inconsistent comment styles

### ISSUE THREAD

**Issue by metacubed** [jkaving/intellij-colors-solarized#155]
I see two separate styles of comments in Java. Some comments show up in gray text, others in red(-ish) text. Is this intentional?

I prefer the gray style - it is unobtrusive and doesn't take away attention until I actually want to read the comments.

Also, in most languages, "Comment Styles" don't inherit from "Language Defaults". They override them, but then set them to the same exact values.

**Comment by aik099** [comment]
Some time ago all comments were grey. Then Java guy came up and told, that comments should now be red, because they are bad thing. The change was made to base comment style and I've seen effects in Java and PHP. Probably not all language comment styles are inheriting from base red comment and that's why you're seeing inconsistencies.

**Comment by jkaving** [comment]
There is quite a bit of discussion about this in issue #67 and issue #127.

To summarise it:
- Yes, it is intentional
- Javadoc comments are grey (or green, for Solarized Light) to be more unobtrusive
  _This is a difference from the original Solarized theme [where Javadoc comments are red](http://ethanschoonover.com/solarized/img/screen-java-dark.png)_
- Line comments are red - to stand out more (argued for in [this article](https://medium.com/@MrJamesFisher/your-syntax-highlighter-is-wrong-6f83add748c9))

**Comment by metacubed** [comment]
I see, thanks @aik099 and @jkaving.

We "document the why" using line comments, so our code turns into a patchy mess with these settings 😆. I'll fork and make changes for our own use.
