### ISSUE TITLE
Does this just change the editor appearance?

### ISSUE THREAD

**Issue by MarKco** [jkaving/intellij-colors-solarized#161]
I installed the colors theme but I just see it in the editor, while the rest of the IDE remains light or dark (as darcula) with the usual grey background.

Is there any way to have the solarized theme on the whole interface?
I'm using Android Studio.

**Comment by aik099** [comment]
This IntelliJ IDEA-based IDE theme only defines colors, not their usage. If particular IDE doesn't apply these colors to the rest of the UI, then you should ask them to do this.

There are custom IDE plugins probably, that extend theme color usage on the UI as well.

**Comment by MarKco** [comment]
Thank you aik

**Comment by jkaving** [comment]
If you want to modify the rest of the UI there are at least a couple of options.

There is the [Color Ide plugin](https://plugins.jetbrains.com/plugin/7055-color-ide), that doesn't seem to be updated but might work.

A newer alternative that seems to have active development is the [Material Theme plugin](https://mallowigi.github.io/material-theme-jetbrains-eap/). This doesn't come with built-in support for the Solarized colors but it includes a custom theme where the colors can be modified.
It would be nice if someone made a pull request for the Material Theme plugin to include Solarized as a built-in theme - see #159.

**Comment by jkaving** [comment]
In the 2019.1 version of IntelliJ-based IDEs it is now possible to  use custom themes (https://blog.jetbrains.com/idea/2019/03/brighten-up-your-day-add-color-to-intellij-idea/)

A Solarized theme, by @snowe2010,  is available at https://github.com/snowe2010/solarized-jetbrains (and in the JetBrains plugin repository at https://plugins.jetbrains.com/plugin/12112-solarized-theme).

**Comment by aik099** [comment]
Unfortunately that repo seems to use copy/pasted theme in different format and therefore any updates in this repo won't be automatically available in there.

Is there any chance to auto-sync them some how?

**Comment by snowe2010** [comment]
There is no need to sync them as my plugin theme maintains the editor theme as well. Technically there is no need to maintain this repo, but if there are changes made here I will be sure to reflect them in my plugin theme as well. I don't foresee the editor theme changing very often though, so a simple Issue or PR on my repo will be enough to keep them updated. I have to release the Plugin manually anyway.

**Comment by jkaving** [comment]
@snowe2010 - It is great that you created a Solarized theme for the new JetBrains IDEs, and that you were so quick to do it. 

I see a few possible approaches here:

**Keep this repo as is**
Keep this repo focused on the color schemes and link to [snowe2010/solarized-jetbrains](https://github.com/snowe2010/solarized-jetbrains) for theming the whole IDE. Make sure to open PRs in that repo when changes are made here.

**Stop maintaining this repo**
As @snowe2010 suggests - stop maintaining this repo.
Any future updates to the Solarized color themes can be done as PRs in [snowe2010/solarized-jetbrains](https://github.com/snowe2010/solarized-jetbrains).
I am a bit reluctant to do that since this repo has a long history, over 3000 stars and is linked to from quite a few places.

**Add IDE themes to this repo**
We could add themes to this repo and make this a complete alternative.
I tried out the theme in [snowe2010/solarized-jetbrains](https://github.com/snowe2010/solarized-jetbrains) and I felt it changed too much of the IDE, making it harder to distinguish the different parts of the UI. So I am a bit tempted to make an attempt at creating "better" Solarized themes.
Doing this would also be a good opportunity to do the refactoring I was thinking about way back in [this comment](https://github.com/jkaving/intellij-colors-solarized/issues/115#issuecomment-174268299).
I guess there might be some problems if we wanted to upload this to the JetBrains plugin repository, since there is already a Solarized theme plugin there now.

At the moment I am leaning towards the third alternative, but I will have to think about this a bit.

**Comment by snowe2010** [comment]
@jkaving it is completely up to you. I am still working on the theme I have created, as it's not really complete. There are a lot of ui options to change to make stuff 'cohesive' enough to call a theme. I'm mostly working off of JetBrains' Dark Purple theme, so if you like that 'style' then you will probably like my final product. It, of course, is completely up to you. Though I don't really like option 2 as that puts a lot of pressure on me 😅
