### ISSUE TITLE
What does this theme from this repo has over the Ethan website one?

### ISSUE THREAD

**Issue by cata0309** [jkaving/intellij-colors-solarized#174]

**Comment by jkaving** [comment]
See https://github.com/altercation/solarized/issues/131 and https://github.com/altercation/solarized/pull/272

The IntelliJ version in the main Solarized repo hasn't been updated since 2011 so it's really outdated. There's been lots of additions and fixes in this repo since then.
(The main Solarized repo actually doesn't seem to have been updated at all, except for the README, since 2013).

This line on the [Solarized web page](https://ethanschoonover.com/solarized/) is therefore a bit misleading:
> Note that through the magic of git-subtree these repositories are all kept in sync, so you can pull any of them and get the most up-to-date version.

Since the main Solarized repo isn't updated anymore you will need to us `git-subtree` yourself. You can clone https://github.com/altercation/solarized and then do this:
```
> git subtree pull --prefix intellij-colors-solarized https://github.com/jkaving/intellij-colors-solarized.git master --squash
```
to update the IntelliJ theme from this repo.
