### ISSUE TITLE
VCS changes highlighting bug

### ISSUE THREAD

**Issue by soshial** [jkaving/intellij-colors-solarized#175]
### 1.
Android Studio Appearance Theme: **Darcula**
Editor Color Scheme: **Darcula**
Comment: **ALL CORRECT**.

<img width="1391" alt="darcula-darcula" src="https://user-images.githubusercontent.com/100644/64006308-ba7f3d80-cb1a-11e9-9255-f44280d5561f.png">

### 2.
Android Studio Appearance Theme: **Darcula**
Editor Color Scheme: **Solarized Dark (Darcula)**
Comment: **WRONG colours in the top vs. CORRECT in the bottom**.

<img width="1411" alt="darcula_solarized_dark_darcula" src="https://user-images.githubusercontent.com/100644/64006304-b9e6a700-cb1a-11e9-9dec-b90e7d4c5455.png">

### 3.
Android Studio Appearance Theme: **Darcula**
Editor Color Scheme: **Solarized Dark**
Comment: **WRONG colours in the top vs. CORRECT in the bottom**

<img width="1378" alt="darcula_solarized_dark" src="https://user-images.githubusercontent.com/100644/64006305-ba7f3d80-cb1a-11e9-8a47-9c5852304c9f.png">

### 4.
Android Studio Appearance Theme: **Darcula**
Editor Color Scheme: **Solarized Light (Darcula)**
Comment: **CORRECT colours in the top** vs. **WRONG in the bottom**

<img width="1417" alt="darcula_solarized_light_darcula" src="https://user-images.githubusercontent.com/100644/64006306-ba7f3d80-cb1a-11e9-8b70-ac009a635d03.png">

### 5.
Android Studio Appearance Theme: Darcula
Editor Color Scheme: Solarized Light
Comment: **ALL CORRECT**.

<img width="1409" alt="darcula_solarized_light" src="https://user-images.githubusercontent.com/100644/64006307-ba7f3d80-cb1a-11e9-8972-6a5bb536e7c9.png">

**Comment by jkaving** [comment]
I think I've managed to improve this so it looks better for Solarized Dark.

It's a bit tricky to get it to look good when you use a light color scheme with a dark theme (or vice versa).
But I don't think that's a common use case, and I guess that's why IntelliJ even warns you if you do it:
![Screenshot 2024-01-04 at 22 43 18](https://github.com/jkaving/intellij-colors-solarized/assets/725090/b5fb591c-ea65-4d30-9684-18e0dd8c6d6d)
