### ISSUE TITLE
Fleet support

### ISSUE THREAD

**Issue by taratyn-tc** [jkaving/intellij-colors-solarized#181]
It looks like [Fleet](https://www.jetbrains.com/fleet/) uses a different format for themes. It would be nice to offer a Solarized theme in that format. 

The docs are not currently very helpful: https://www.jetbrains.com/help/fleet/color-themes.html.

**Comment by jkaving** [comment]
I agree - it would be nice to have a Solarized theme for Fleet.
But since the format is completely different, I don't think it makes much sense to add it to this repo.
It's probably better to do that in a separate repo.

I did find [this YouTrack issue](https://youtrack.jetbrains.com/issue/FL-13018) that's about adding more color themes to Fleet. It does mention Solarized, it's open and has the priority "Major" (whatever that means).
So it could be a good idea to vote for that issue and adding a comment about wanting Solarized.

It does seem pretty easy to modify the JSON file for the color scheme.
I was able to change the background color by simply following the documentation you linked and changing the value for `palette.White`:
![Screenshot 2024-01-04 at 21 31 40](https://github.com/jkaving/intellij-colors-solarized/assets/725090/87fcc0ea-518a-4951-9346-8f61863c213f)

**Comment by jkaving** [comment]
Many of the colors seem to be defined in terms of the palette in the end of the JSON file:
```json
  "palette": {
    "White": "ffffff",
    "Gray 110": "f2f2f2",
    "Gray 100": "eaeaea",
    "Gray 90": "e2e2e2",
    "Gray 80": "d8d8d8",
    "Gray 70": "c2c2c2",
    "Gray 60": "a0a0a0",
    "Gray 50": "898989",
    "Gray 40": "767676",
    "Gray 30": "484848",
    "Gray 20": "383838",
    "Gray 10": "181818",
    "Black": "000000",
    "Blue 110": "f4f8fd",
    "Blue 100": "edf4fc",
    "Blue 90": "d8e8fa",
    "Blue 80": "bfd9f8",
    "Blue 70": "a2c8f7",
    "Blue 60": "6daaf7",
    "Blue 50": "3691f9",
    "Blue 40": "1a85f6",
    "Blue 30": "0273eb",
    "Blue 20": "0c6ddd",
    "Blue 10": "1565c8",
    "Red 90": "fcf1f3",
    "Red 80": "fcf1f3",
    "Red 70": "f3b4bf",
    "Red 60": "ee8a9b",
    "Red 50": "ee8a9b",
    "Red 40": "ea4b67",
    "Red 30": "d93953",
    "Red 20": "ce364d",
    "Red 10": "c03248",
    "Green 90": "ecf5f1",
    "Green 80": "c7ecdc",
    "Green 70": "91d2b8",
    "Green 60": "61b696",
    "Green 50": "4ca988",
    "Green 40": "3ea17f",
    "Green 30": "028764",
    "Green 20": "07805f",
    "Green 10": "13664e",
    "Yellow 70": "fef7eb",
    "Yellow 60": "fedfb0",
    "Yellow 50": "fecf87",
    "Yellow 40": "f8ab17",
    "Yellow 30": "e1971b",
    "Yellow 20": "d08a1e",
    "Yellow 10": "9a651e",
    "Purple 20": "a842eb",
    "Purple 10": "a336e9",
    "Blue": "1749bd",
    "Brown": "664229",
    "Green": "086e14",
    "Lime": "616605",
    "Pink": "a31d8d",
    "Plum": "944a9e",
    "Teal": "14646e",
    "Teal Dark": "47676b",
    "Violet": "5511bf",
    "Violet 70": "e3e1fe",
    "Violet 60": "c3befb",
    "Violet 50": "a39bf9",
    "Violet 40": "6d60f4",
    "Violet 30": "6658f3",
    "Violet 20": "5a4ce5",
    "Violet 10": "4d40d8",
    "Orange": "bf4a02",
    "Transparent": "ffffff0%"
  }
```

Some of these are easy to replace with Solarized colors.
The tricky part is coming up with good values for the different tones of Gray, Blue, Red, Green, Yellow, Purple and Violet.
