### ISSUE TITLE
base03 color is not dark enough in Idea12CE

### ISSUE THREAD

**Issue by gsshiva** [jkaving/intellij-colors-solarized#46]
The background color is correctly set to base03 in the Solarized pallete appears to be lighter compared to the color on other apps, like iTerm2 (MacOS) and Vim. See attached picture of iTerm2 and Idea12CE. The same issue appears on Windows 7 as well. Not sure what the issue could be. BTW, I see the same issue with the the IntelliJ colors on main (https://github.com/altercation/solarized) repository as well. What gives ?
![solarized-idea12](https://f.cloud.github.com/assets/4551841/574014/6dd2ab04-c7be-11e2-81d3-65c3c63b6cb4.png)

**Comment by jkaving** [comment]
As mentioned before - this problem is fixed for me when running IntelliJ IDEA with Java 7 or 8.

There is now an early access version of IntelliJ IDEA 14.1 using a bundled custom-built Java 8 JDK at https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP 

With this version I don't get the other problems i got using a newer JDK (shortcut commands using 'Alt' not working, screen flickering etc.).

**Comment by geoelectric** [comment]
As a final followup, I did end up trying out the PyCharm with bundled Java 8, and the problem went away there as well (no big surprise given the last comment). I don't see any other issues introduced, so I'll stick with this.

**Comment by jkaving** [comment]
Closing this issue since the problem has been fixed by IntelliJ versions bundling Java 8.
