### ISSUE TITLE
missing tons of colors for java

### ISSUE THREAD

**Issue by pdeva** [jkaving/intellij-colors-solarized#90]
The current theme for java only does basic syntax highlighting.

However, Intellij can do semantic highlighting, meaning it can highlight things like: 

method calls, static method calls, local variables, local variables assigned more than once, etc.

The current theme does none of that. So using this theme actually results in a loss of visual information.

Please add themes for more java elements supported by intellij.

**Comment by alexey-danilov** [comment]
I have exactly the same impression - that lot of important information is just left out. IMHO the problem here is that solarized color palette just does not have enough colors for that. Don't get me wrong - it is an excellent choice for terminal, for example, but for IDE I finally decided to develop my own color theme (after trying a _ton_ of ready available).

In the end it is a matter of preference and you just cannot provide a solution perfect for everyone.

**Comment by jkaving** [comment]
Yes, IntelliJ IDEA has great support for syntax highlighting.
But this repository aims to provide an IntelliJ IDEA version of the Solarized color scheme as described at http://ethanschoonover.com/solarized
As @alexey-danilov says, a problem is that Solarized is limited to 16 colors:
> Solarized is a sixteen color palette (eight monotones, eight accent colors) designed for use with terminal and gui applications.

If you like the Solarized color scheme but want to have more colors, you are free to make your own scheme based on this one (but if you do you should probably not call it Solarized).

**Comment by mathissimo** [comment]
I googled my way here, because I was also unsatisfied with the 'plain' syntax highlighting from idea.

As expected, others (**@alexey-danilov**, **pdeva**?)  have already setup a better syntax highlighting. Any chance that there are **some sources to share**?
Thank you!

And thank you to **@jkaving** for the solarized scheme!

**Comment by alexey-danilov** [comment]
@mathissimo I've created my own color scheme, but have not published it [yet]. If you're interested, I can send you idea settings file... but I guess the best option is to build your own :)

**Comment by mathissimo** [comment]
Hi @alexey-danilov - thanks for the offer, which I am happy to take! 
My own trials have not gone far, yet. So I am really curious for your solution.

Maybe you could post it here or a permanent link (e.g. gist) to the file, so other may benefit as well.

**Comment by alexey-danilov** [comment]
here you go :) https://www.dropbox.com/s/chgm5wgw8aef7u8/adani_color_scheme.jar?dl=0
