### ISSUE TITLE
Notification background color is too bright

### ISSUE THREAD

**Issue by alexey-danilov** [jkaving/intellij-colors-solarized#94]
I find that notification background in solarized dark scheme is too bright. Cobined with rather light notification foreground font color, this makes text hard to read during daylight.

My suggestion is to change it to 59604A. This color is not from a solarized palette, but the one used in IDEA's interface.

![prtscr capture](https://cloud.githubusercontent.com/assets/4075759/6780236/0f4f7cba-d16c-11e4-8548-f95354a0d843.jpg)

![prtscr capture_2](https://cloud.githubusercontent.com/assets/4075759/6780235/0f4e656e-d16c-11e4-8faa-291a9d4272b2.jpg)

**Comment by jkaving** [comment]
This seems to be the same issue as #79.

**Comment by alexey-danilov** [comment]
that's true, but the referenced issues is not resolved (somehow), and it lacks a proper replacement color suggestion.

**Comment by jkaving** [comment]
Yep - this issue is a good reminder that this needs to be fixed :-)

Which version of IDEA are you using?

I'm using the latest EAP version and I don't get the light foreground color in this notification:
![screenshot of screenfloat 2015-03-24 09 31 33](https://cloud.githubusercontent.com/assets/725090/6798082/d39028ca-d209-11e4-8d13-0179228eff1e.png)

Changing to your suggestion actually makes it worse:
![screenshot of intellij idea-eap 2015-03-24 09 41 48](https://cloud.githubusercontent.com/assets/725090/6798099/02925e54-d20a-11e4-8b89-2ae3cc6e9e7b.png)

By the way - where/how do you get the notification in your screenshots?

**Comment by alexey-danilov** [comment]
That's strange. I have installed the version you have mentioned and still see the very same colors.
How to get screenshots: there are a couple of ways. The ones I use are:
1). Use "compare with same repository version" on the file which has not changed.
2). Copy contents of the file -> use "compare with clipboard" action on the same file.

**Comment by jkaving** [comment]
Do you mean that you see the same colors as in your screenshot?

This is how it looks for me:
![screenshot of intellij idea-eap 2015-03-24 12 17 51](https://cloud.githubusercontent.com/assets/725090/6800547/d1f227a0-d21f-11e4-9b82-42136ac71fd0.png)

I didn't specify that, but I'm actually using the 14.1 EAP version with custom bundled JDK (https://confluence.jetbrains.com/display/IDEADEV/IDEA+14.1+EAP).
I'm running on OS X Yosemite.

**Comment by alexey-danilov** [comment]
Yes, I see the same colors as in my screenshot, and yes, I have the same 14.1 eap version as you do.
My OS is win7 x64.

**Comment by fmorato** [comment]
The notification background color also look too bright on Linux. : / using 15 now

**Comment by jkaving** [comment]
I just realized what the difference was - you where using the Darcula L&F while I was still using the default L&F (I only switched to the Solarized Dark color theme).
The foreground color used for the notifications seem to differ between the L&Fs, so we need to use different background colors for them.
I have now updated the build script so that it generates the Darcula versions with a different notification background.
